$(document).ready(function() {
    $('#comptitle').on('click',function(){
        $('#comp').toggle();
    });
    $('#svmtitle').on('click',function(){
        $('#svm').toggle();
    });
    $('#rftitle').on('click',function(){
        $('#rf').toggle();
    });
    $('#firsttitle').on('click',function(){
        $('#first').toggle();
    });
    $('#standardtitle').on('click',function(){
        $('#standard').toggle();
    });
    $('#updatestitle').on('click',function(){
        $('#updates').toggle();
    });
    $('#nntitle').on('click',function(){
        $('#nn').toggle();
    });
});
